name: Lint and Style Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-style:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3'

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("lintr", "styler"))'

    - name: Lint code
      run: |
        Rscript -e 'library(lintr); lint_dir(path = ".", linters = with_defaults())'

    - name: Check styling
      run: |
        Rscript -e 'library(styler); style_dir(".", dry = "off")'

- name: Commit and push changes
  run: |
    git config user.name "github-actions"
    git config user.email "actions@github.com"
    git add .
    git commit -m "Style fixes applied by GitHub Actions" || echo "No changes to commit"
    git push
